### ISSUE TITLE
Error en compilación

### ISSUE THREAD

**Issue by clawgrip** [ctt-gob-es/fire#44]
En su estado actual, el subproyecto "fire-admin-persistence" no compila por no encontrar las clases del paquete "es.gob.fire.persistence.permissions":

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project fire-admin-persistence: Compilation failure: Compilation failure:
[ERROR] C:\Users\tomas.capote\eclipse-workspace\fire\fire-admin-persistence\src\main\java\es\gob\fire\persistence\service\impl\UserService.java:[51,42] error: package es.gob.fire.persistence.permissions does not exist
[ERROR] C:\Users\tomas.capote\eclipse-workspace\fire\fire-admin-persistence\src\main\java\es\gob\fire\persistence\service\impl\UserService.java:[52,42] error: package es.gob.fire.persistence.permissions does not exist

![image](https://github.com/ctt-gob-es/fire/assets/5889052/7d2422ad-0389-47d1-a129-3c4957f45c40)

**Comment by Gamuci** [comment]
Cambios subidos. Por favor, confirma que compila correctamente y cierra el issue en caso de que así sea.

Gracias.

**Comment by clawgrip** [comment]
Ya compila correctamente ¡Gracias!
