### ISSUE TITLE
java.lang.ClassNotFoundException: es.gob.fire.server.admin.service.AppService

### ISSUE THREAD

**Issue by pieldeyeti** [ctt-gob-es/fire#7]
Error al desplegar el componente de administración debido a que el servlet es.gob.fire.server.admin.service.AppService se ha renombrado a es.gob.fire.server.admin.service.NewAppService. Es necesario actualizar el fichero web.xml para que refleje dichos cambios.

**Comment by Gamuci** [comment]
Parece que el nombre del servicio estaba declarado mediante una anotación además de en el web.xml. Según se cargase una u otra funcionaba o no. Algo parecido ocurría con otros servicios. Ya se ha corregido.

Gracias por el aviso.
