### ISSUE TITLE
Certificados caducados

### ISSUE THREAD

**Issue by rebecop** [ctt-gob-es/fire#9]
Hola,

sólo indicar que los certificados proporcionados para el servicio de prueba:
fire/clavefirma-test-services/src/main/resources/testservice/

se encuentran caducados a 4 de Mayo de 2019, por lo que ahora mismo es complicado hacer pruebas con dichos certificados.

Muchas gracias y saludos.

**Comment by Gamuci** [comment]
Gracias por el aviso.

Hemos actualizado el certificado de pruebas. Si estás usando el WAR publicado, puedes abrirlo y sustituir los ficheros "00001.p12" y "new.p12" por los que hay en el repositorio: [https://github.com/ctt-gob-es/fire/tree/master/clavefirma-test-services/src/main/resources/testservice](https://github.com/ctt-gob-es/fire/tree/master/clavefirma-test-services/src/main/resources/testservice).
